### ISSUE TITLE
error 404 by octokit

### ISSUE THREAD

**Issue by Schnullerpip** [freeedcom/ai-codereviewer#17]
Hi

I am seeing the following error when running this action:
![image](https://github.com/freeedcom/ai-codereviewer/assets/3928616/35f3befb-3568-4ab0-8bed-5cd0ee7cefc3)

This error is being thrown by the @octokit/request library. 
I myself have no experience with octokit and unfortunately am unable to examine your usage of the library :( 

presumably unrelated but just in case:
I am using the recommended workflow from the README and I use a valid openai api key + github token.

**Comment by Schnullerpip** [comment]
I tried to give the code a check. Could it be, thaat the `getPrDetails` function is unable to retrieve the pull as I am not the **owner** of the repository, that I am working on?

**Comment by villesau** [comment]
It looks like there might be some issue with the access token. Do your token have an access to the repo? Those are hard to debug, I've struggled with the same at some point. And the screenshot does not give much other hints that would help debugging unfortunately.

**Comment by Schnullerpip** [comment]
you are correct - I can confirm the issue lies not within this project 👍

**Comment by villesau** [comment]
Nice! When I was originally developing this I struggled with tokens a lot too. It was far from clear whether the issue was in code or the token 😅

**Comment by DanielRiveraHQ** [comment]
Hey guys, I'm having a similar issue about token permissions. Do you have a hint or point me in the right direction?

I forked the code review repo, and the repository where I'm trying to implement reviews is a private repo. I can send screenshots of how I have setup the action settings in both repos if needed. 

Thank you in advance!

**Comment by DanielBelz1997** [comment]
> Hey guys, I'm having a similar issue about token permissions. Do you have a hint or point me in the right direction?
> 
> I forked the code review repo, and the repository where I'm trying to implement reviews is a private repo. I can send screenshots of how I have setup the action settings in both repos if needed.
> 
> Thank you in advance!

having the same problem. @fettstorch how did you fixed that?
